
services:
# for localhost database
#  postgresdb:
#    image: postgres:15-alpine
#    container_name: vpm_db
#    restart: always
#    environment:
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#      POSTGRES_DB: mydatabase
#    ports:
#      - "5432:5432"

  app:
    build: .
    ports: 
      - "8080:8080"
    environment:
    # database connection from URL
    # configured in .env 
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
